Use "ref" instead of "version" to lock instance_profile module in the example
Github source doesn't support version constraints:

* terraform 0.11.14 ignores the version constraints and loads latest version

> Initializing modules...
> - module.instance_profile
>   Getting source "github.com/traveloka/terraform-aws-iam-role.git//modules/instance"

* terraform 0.12.6 fails with

> Error: Invalid version constraint
>
> Cannot apply a version constraint to module "instance_profile" (at
> 02-instance_role.tf:1) because it has a non Registry URL.